#!/bin/bash

rubber --clean Main-Doc

rm *.ist* *.pdf* *.mtc* *.xml *.maf *.ist *.glg *.glo *.gls *.slg *.syg *.syi *-blx.bib*

pdflatex main-doc.tex
pdflatex main-doc.tex
pdflatex main-doc.tex
bibtex main-doc
makeglossaries main-doc
pdflatex main-doc.tex
pdflatex main-doc.tex
pdflatex main-doc.tex

# chmod 700 run_engines
# ./run_engines
