#!/bin/bash

rubber --clean PhD-Dissertation

rm -f *.ist* *.fls* *.mtc* *.xml *.maf *.ist *.glg *.glo *.gls *.slg *.syg *.syi *-blx.bib*

<<EXCLUDE
pdflatex --synctex=1 PhD-Dissertation.tex
pdflatex --synctex=1 PhD-Dissertation.tex
pdflatex --synctex=1 PhD-Dissertation.tex
bibtex PhD-Dissertation
makeglossaries PhD-Dissertation
pdflatex --synctex=1 PhD-Dissertation.tex
pdflatex --synctex=1 PhD-Dissertation.tex
pdflatex --synctex=1 PhD-Dissertation.tex
EXCLUDE

# chmod +x run-tex
# ./run-tex
